# Shared default hosts for both Bash and PowerShell suites.
# Format:
#   ipv4=<host>
#   ipv6=<host>

ipv4=netcologne.de
ipv4=google.com
ipv4=wikipedia.org
ipv4=amazon.de

ipv6=netcologne.de
ipv6=google.com
ipv6=wikipedia.org
